=head1 NAME

Retooling. Going to use git as the default backend for everything.

Check out example.bs.

=head1 FIRST

This is a first-pass braindump. Take with salt and flame me at tobert@gmail.com,
@AlTobey on twitter, or "tobert" on Freenode IRC ##devops or ##infra-talk.

=head1 CHOICES

Perl: it's still my strongest language, it's everywhere, and it's stable, both API and runtime

=head1 TODO

1.) Figure out some kind of a process tree session that makes sense for bespoke calling
bs scripts that call bespoke and so on in such a way that it can do stateful things. This
is going to be most critical when figuring out the dependency graph on the fly.

2.) see what options are available over git/git-http protocol for single object &
partial exports.

=cut

